- config/webpacker.yml
> Revert "11017: Config webpacker"

- Gemfile
- Gemfile.lock
- app/validators/reduce_validator.rb
- app/validators/uniqueness_validator.rb
http://www.redmine.dtpebike.vn/issues/9
> 11029: Create validator.

- db/seeds/development.rb
http://www.redmine.dtpebike.vn/issues/14
> 14: Not TRUNCATE table admins when seed data.

- .gitignore
- db/migrate/20201112171035_remove_devise_from_users.rb
- db/schema.rb
http://redmine.dtpebike.vn/issues/13
> 11002_manh: Delete fields table users

- .github/workflows/ruby.yml
- .gitignore
- Gemfile
- Gemfile.lock
- app/forms/base_form.rb
- app/forms/rooms_form.rb
- app/forms/users_form.rb
- app/models/user.rb
- spec/factories/floors.rb
- spec/factories/rooms.rb
- spec/factories/users.rb
- spec/forms/rooms_form_spec.rb
- spec/forms/users_form_spec.rb
- spec/models/admin_spec.rb
- spec/models/floor_spec.rb
- spec/models/room_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
http://www.redmine.dtpebike.vn/issues/17
> 17: Add gem simplecov and write Rspec.

- .gitignore
- app/models/user.rb
- lib/tasks/default_data.rake
http://redmine.dtpebike.vn/issues/16
> 3_manh:Delete Devise for User

- spec/serializers/floor_serializer_spec.rb
- spec/serializers/room_serializer_spec.rb
- spec/serializers/user_serializer_spec.rb
http://www.redmine.dtpebike.vn/issues/23
> 23: Spec serializers.

- .github/workflows/ruby.yml
- app/controllers/api/users/rooms_controller.rb
- app/controllers/users_controller.rb
- app/forms/batch_create/users_form.rb
- app/forms/users_form.rb
- app/javascript/api/users.js
- app/javascript/component_users/editUser.vue
- app/javascript/component_users/newUsers.vue
- app/javascript/components/inputSelect2.vue
- app/javascript/components/inputText.vue
- app/javascript/mixins/handle_errors.js
- app/javascript/newUser.vue
- app/javascript/packs/application.js
- app/javascript/store/modules/user.js
- app/javascript/user.vue
- app/serializers/user_serializer.rb
- app/views/api/users/rooms/index.json.jbuilder
- app/views/users/new.html.slim
- config/locales/controller.en.yml
- config/routes/api.rb
- spec/forms/batch_create/users_form_spec.rb
- spec/forms/users_form_spec.rb
http://www.redmine.dtpebike.vn/issues/3
> 11025: Create users.

- app/assets/stylesheets/_menu.scss
- app/assets/stylesheets/styles.scss
- app/helpers/application_helper.rb
- app/views/layouts/application.html.slim
- app/views/shared/_menu.html.slim
https://ruby-training.tk/issues/8
> 8: Create top menu

- app/javascript/components/inputSelect2.vue
https://ruby-training.tk/issues/24
> 24: Edit Room

- app/javascript/components/contextMenu/contextMenu.vue
https://ruby-training.tk/issues/26
> 26:[Bug]Edit and delete User

- app/views/shared/_menu.html.slim
http://www.redmine.dtpebike.vn/issues/28
> 28: [Bug] Display on smartphone.

- config/application.rb
http://www.redmine.dtpebike.vn/issues/29
> 29: Fix position rack-dev-mark.

- app/javascript/components/inputSelect2.vue
http://www.redmine.dtpebike.vn/issues/32
> 32: Create contracts.

- app/javascript/component_users/deleteUser.vue
- app/javascript/components/inputToggleSwitch.vue
http://www.redmine.dtpebike.vn/issues/30
> 30: Confirm before deleting.

- app/assets/stylesheets/_custom_table.scss
- app/assets/stylesheets/styles.scss
- app/controllers/contracts_controller.rb
- app/javascript/api/contracts.js
- app/javascript/component_contracts/detailContract.vue
- app/javascript/component_contracts/rowContract.vue
- app/javascript/component_contracts/tableContracts.vue
- app/javascript/component_floors/rowRoom.vue
- app/javascript/component_users/tableUsers.vue
- app/javascript/components/fieldOnlyView.vue
- app/javascript/store/modules/contract.js
- app/models/contract.rb
- app/serializers/detail_contract_serializer.rb
- lib/tasks/default_data.rake
- spec/models/contract_spec.rb
- spec/serializers/detail_contract_serializer_spec.rb
http://www.redmine.dtpebike.vn/issues/22
> 22: Show contract

- .env.sample
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/registrations_controller.rb
- app/views/devise/shared/_links.html.slim
- config/deploy/development.rb
- db/fixtures/admin.rb
- setup_rubydev.md
http://www.redmine.dtpebike.vn/issues/31
> 31: Prepare env staging deploy

- app/javascript/component_contracts/rowContract.vue
http://www.redmine.dtpebike.vn/issues/35
> 35: Show details contract with double click.

- config/deploy/development.rb
- config/webpack/environment.js
- config/webpack/loaders/sass.js
- package.json
- yarn.lock
http://www.redmine.dtpebike.vn/issues/38
> 38: [Staging] Fix css in vue js.

- app/javascript/component_contracts/rowContract.vue
- app/javascript/component_contracts/tableContracts.vue
- app/serializers/contract_serializer.rb
- spec/serializers/contract_serializer_spec.rb
- spec/serializers/detail_contract_serializer_spec.rb
- spec/serializers/floor_serializer_spec.rb
- spec/serializers/room_serializer_spec.rb
- spec/serializers/user_serializer_spec.rb
http://www.redmine.dtpebike.vn/issues/34
> 34: Show status contracts.

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/css_files.scss
- app/assets/stylesheets/styles.scss
- config/deploy/development.rb
- package.json
- yarn.lock
http://www.redmine.dtpebike.vn/issues/36
> 36: [Staging] Select room error in /users/new.

- app/assets/stylesheets/_custom_toggle_switch.scss
- app/javascript/component_users/rowUser.vue
- app/javascript/component_users/tableUsers.vue
http://www.redmine.dtpebike.vn/issues/39
> 39: Edit/Delete User button

- app/controllers/contracts_controller.rb
- app/forms/contracts_form.rb
- app/javascript/api/contracts.js
- app/javascript/component_contracts/rowContract.vue
- app/javascript/component_contracts/tableContracts.vue
- app/javascript/component_contracts/terminateContract.vue
- app/javascript/store/modules/contract.js
- app/presenters/users_presenter.rb
http://www.redmine.dtpebike.vn/issues/21
> 21: Terminate contract.

- app/javascript/component_users/deleteUser.vue
http://www.redmine.dtpebike.vn/issues/33
> 33: Checked value always false when choose delete user.

- .env.sample
- config/deploy/development.rb
- config/deploy/staging.rb
https://redmine.dtpebike.vn/issues/46
> 46:config staging capistrano

- .env.sample
- config/deploy/development.rb
- config/deploy/staging.rb
https://redmine.dtpebike.vn/issues/46
> Config capistrano staging

- app/assets/stylesheets/styles.scss
- app/javascript/packs/application.js
- app/javascript/stylesheets/application.scss
- app/views/layouts/application.html.slim
https://redmine.dtpebike.vn/issues/37
> 37:[Staging] Cannot load @fontawesome

- Gemfile
- Gemfile.lock
- app/javascript/component_users/rowUser.vue
- app/javascript/component_users/tableUsers.vue
- app/presenters/contracts_presenter.rb
- app/presenters/users_presenter.rb
- app/serializers/user_serializer.rb
- config/environments/development.rb
- spec/serializers/user_serializer_spec.rb
https://redmine.dtpebike.vn/issues/54
> 54: Add room_number to screen table users

- app/views/shared/_menu.html.slim
- config/locales/views.yml
https://redmine.dtpebike.vn/issues/49
> 49: [v1.1] Create button download sample file

- config/environments/development.rb
https://redmine.dtpebike.vn/issues/56
> 56:Fix issue restart rails when change code

- app/controllers/contracts_controller.rb
- app/forms/extend_contract_form.rb
- app/javascript/api/contracts.js
- app/javascript/component_contracts/extendContract.vue
- app/javascript/component_contracts/newContract.vue
- app/javascript/component_contracts/rowContract.vue
- app/javascript/component_contracts/tableContracts.vue
- app/javascript/component_contracts/terminateContract.vue
- app/javascript/component_floors/editRoom.vue
- app/javascript/component_users/deleteUser.vue
- app/javascript/component_users/editUser.vue
- app/javascript/component_users/newUsers.vue
- app/javascript/components/fieldConfirm.vue
- app/javascript/components/inputNumber.vue
- app/javascript/components/inputNumberCurrency.vue
- app/javascript/components/inputRadioButtons.vue
- app/javascript/components/inputSelect2.vue
- app/javascript/components/inputText.vue
- app/javascript/components/inputToggleSwitch.vue
- app/javascript/contract.vue
- app/javascript/mixins/max_min_value.js
- app/javascript/mixins/max_value.js
- app/javascript/store/modules/contract.js
- app/javascript/store/modules/user.js
- app/models/floor.rb
- app/models/room.rb
- app/serializers/room_serializer.rb
- spec/forms/extend_contract_form_spec.rb
- spec/serializers/room_serializer_spec.rb
https://redmine.dtpebike.vn/issues/51
> 51: [v1.1] Contract extension

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/users.scss
- app/controllers/batch_create/users_controller.rb
- app/forms/batch_create/users_import_form.rb
- app/forms/users_form.rb
- app/javascript/api/users.js
- app/javascript/component_users/newUsers.vue
- app/javascript/components/uploadFile.vue
- app/javascript/locales/modules/en.js
- app/javascript/newUser.vue
- app/javascript/packs/application.js
- app/javascript/store/modules/user.js
- app/uploaders/user_file_uploader.rb
- config/application.rb
- config/initializers/config.rb
- config/locales/controller.en.yml
- config/locales/form.en.yml
- config/locales/model.en.yml
- config/routes.rb
- config/settings.yml
- docker-compose.yml
- lib/tasks/default_data.rake
- package.json
- yarn.lock
https://redmine.dtpebike.vn/issues/50
> 50: [v1.1] Import user with file xlsx

- config/locales/form.vi.yml
https://redmine.dtpebike.vn/issues/67
> 67: i18n get error when batch create user

- app/models/contract.rb
- app/models/invoice.rb
- app/models/item/electric.rb
- app/models/item/internet.rb
- app/models/item/parking_fee.rb
- app/models/item/service.rb
- app/models/item/water.rb
- app/models/resource_item.rb
- app/models/service_item.rb
- db/migrate/20210131020822_create_invoices.rb
- db/migrate/20210131020923_create_resource_items.rb
- db/migrate/20210131020948_create_service_items.rb
- db/schema.rb
https://redmine.dtpebike.vn/issues/74
> 74: Init DB about Invoice, ResourceItem & Service Item

- app/forms/contracts_form.rb
http://redmine.dtpebike.vn/issues/81
> 81: Fix terminate contract.

- app/javascript/component_floors/rowFloor.vue
- app/javascript/component_floors/rowRoom.vue
- db/seeds/production.rb
- lib/tasks/default_data_prd.rake
http://redmine.dtpebike.vn/issues/77
> 77:Seed data for production

- app/controllers/invoices_controller.rb
- app/forms/batch_create/invoices_form.rb
- app/forms/invoice_form.rb
- app/javascript/invoice.vue
- app/javascript/packs/application.js
- app/models/contract.rb
- app/models/invoice.rb
- app/models/room.rb
- app/views/invoices/index.html.slim
- app/views/invoices/new.html.slim
- config/routes.rb
- config/settings.yml
- db/migrate/20210131020822_create_invoices.rb
- db/seeds/development.rb
- lib/tasks/default_data.rake
http://redmine.dtpebike.vn/issues/79
> 79: Build form object

- app/javascript/component_users/newUsers.vue
- app/javascript/components/fieldConfirm.vue
- app/javascript/components/inputNumber.vue
- app/javascript/components/inputNumberCurrency.vue
- app/javascript/components/inputRadioButtons.vue
- app/javascript/components/inputSelect2.vue
- app/javascript/components/inputText.vue
- app/views/devise/registrations/new.html.slim
http://redmine.dtpebike.vn/issues/90
> 90:[Fixbug] Wrong spelling mistake from "Label" to "Lable"

- app/forms/invoice_form.rb
- app/javascript/api/invoices.js
- app/javascript/component_invoices/detailInvoice.vue
- app/javascript/component_invoices/rowInvoice.vue
- app/javascript/component_invoices/tableInvoices.vue
- app/javascript/locales/modules/en.js
- app/javascript/locales/modules/vi.js
- app/javascript/store/modules/invoice.js
- docker-compose.yml
http://redmine.dtpebike.vn/issues/85
> 85:Show specific invoice modal

- app/forms/batch_create/invoices_form.rb
- app/forms/invoice_form.rb
- app/models/resource_item.rb
- app/models/service_item.rb
- app/serializers/invoice_serializer.rb
- config/locales/model.en.yml
- config/locales/model.vi.yml
- config/settings.yml
- lib/tasks/default_data.rake
http://redmine.dtpebike.vn/issues/91
> 91: [Support] Unit in HTML invoice

- app/forms/batch_create/invoices_form.rb
- app/javascript/component_invoices/batch_create/newInvoices.vue
- app/javascript/component_invoices/batch_create/rowInvoiceForm.vue
- app/javascript/components/inputDate.vue
- app/javascript/locales/modules/en.js
- app/javascript/locales/modules/vi.js
- app/javascript/printInvoice.vue
http://redmine.dtpebike.vn/issues/92
> 92: Add field export date in invoice form

- app/forms/batch_create/invoices_form.rb
- app/forms/invoice_form.rb
- db/migrate/20210314082348_add_ratio_day_lived_to_invoice.rb
- db/schema.rb
http://redmine.dtpebike.vn/issues/93
> 93: [DB] Add ratio_day_lived to table invoices

- app/services/download_invoice_service.rb
http://redmine.dtpebike.vn/issues/94
> [Fix] Show total_money with only decimal , non of them is floating number

- Gemfile.lock
- app/controllers/invoices_controller.rb
- app/forms/invoice_form/destroy.rb
- app/javascript/api/invoices.js
- app/javascript/component_invoices/deleteInvoice.vue
- app/javascript/component_invoices/rowInvoice.vue
- app/javascript/component_invoices/tableInvoices.vue
- app/javascript/locales/modules/en.js
- app/javascript/locales/modules/vi.js
- app/javascript/store/modules/invoice.js
- app/models/invoice.rb
- app/models/resource_item.rb
- app/models/service_item.rb
- app/serializers/invoice_serializer.rb
- config/routes.rb
- db/migrate/20210324142329_add_soft_delete_to_items_invoice.rb
- db/schema.rb
http://redmine.dtpebike.vn/issues/87
> 87: Delete invoice button

- app/javascript/component_invoices/detailInvoice.vue
http://redmine.dtpebike.vn/issues/95
> 95: 2 ID in 1 view

- Gemfile.lock
http://redmine.dtpebike.vn/issues/99
> 99: Update mimemagic version into 0.3.10

- app/controllers/invoices_controller.rb
- app/forms/invoice_form/new.rb
- app/javascript/api/invoices.js
- app/javascript/component_invoices/newInvoices.vue
- app/javascript/newInvoice.vue
- app/javascript/store/modules/contract.js
- app/javascript/store/modules/invoice.js
- app/models/invoice.rb
- app/policies/invoice_form/new_policy.rb
- config/locales/controller.en.yml
- config/locales/controller.vi.yml
http://redmine.dtpebike.vn/issues/97
> 97: Constrain unique invoice for new 1 invoice screen

- app/forms/contracts_form.rb
- app/javascript/store/modules/floor.js
- spec/forms/contracts_form_spec.rb
http://redmine.dtpebike.vn/issues/102
> 102: QA1 : Change status to hired when save new contract

- app/models/contract.rb
- app/presenters/contracts_presenter.rb
http://redmine.dtpebike.vn/issues/103
> 103: QA2 : Sort contract with status and date_created

- app/forms/contracts_form.rb
- config/locales/form.en.yml
- config/locales/form.vi.yml
- spec/forms/contracts_form_spec.rb
http://redmine.dtpebike.vn/issues/106
> 106 : Validate end date greater than start date in new invoice screen

- app/controllers/invoices_controller.rb
- app/forms/invoice_form/base.rb
- app/javascript/component_invoices/editInvoice.vue
- app/javascript/component_invoices/newInvoices.vue
- app/javascript/store/modules/invoice.js
http://redmine.dtpebike.vn/issues/104
> 104 : Not allow edit room_price in edit invoice modal

- config/deploy/staging.rb
http://redmine.dtpebike.vn/issues/46
> 46 : [Staging] Setup infrastructure of staging server VN

- app/presenters/invoices_presenter.rb
- config/settings.yml
http://redmine.dtpebike.vn/issues/108
> 109: QA7 : Support show 30 invoices per page in index invoices screen

- config/locales/devise.en.yml
- config/locales/devise.vi.yml
http://redmine.dtpebike.vn/issues/109
> QA8 : i18n show warning try login when already logged in

- app/javascript/locales/modules/en.js
- app/javascript/locales/modules/vi.js
- app/javascript/packs/application.js
- app/javascript/printInvoice.vue
- package.json
- yarn.lock
http://redmine.dtpebike.vn/issues/110
> 110: Capture screen show invoice

- config/locales/model.en.yml
- config/locales/model.vi.yml
http://redmine.dtpebike.vn/issues/111
> 111: QA9 : Fix I18n of invalid day used per month in edit invoice screen

- app/assets/stylesheets/_custom_table.scss
- app/controllers/batch_create/invoices_controller.rb
- app/forms/batch_create/invoices_form.rb
- app/javascript/api/invoices.js
- app/javascript/component_invoices/batch_create/newInvoices.vue
- app/javascript/store/modules/invoice.js
http://redmine.dtpebike.vn/issues/115
> 115: [Urgent] Fix No method error for date_export.end_of_month

- config/deploy/staging.rb
- nginx/conf.d/myapp.conf
http://redmine.dtpebike.vn/issues/113
> 113 : Config Premium VPS server for quanlitoanha.com

- app/assets/stylesheets/_custom_table.scss
- app/controllers/batch_create/invoices_controller.rb
- app/forms/batch_create/invoices_form.rb
- app/javascript/component_invoices/batch_create/newInvoices.vue
- app/javascript/component_invoices/batch_create/rowInvoiceForm.vue
- app/javascript/locales/modules/en.js
- app/javascript/locales/modules/vi.js
- config/locales/controller.en.yml
- config/locales/controller.vi.yml
- package.json
- yarn.lock
http://redmine.dtpebike.vn/issues/114
> 114: Add checkbox to batch create invoice new screen

- app/controllers/batch_create/invoices_controller.rb
- app/forms/batch_create/invoices_form.rb
- app/forms/invoice_form/new.rb
- app/javascript/api/invoices.js
- app/javascript/component_invoices/batch_create/newInvoices.vue
- app/javascript/component_invoices/batch_create/rowInvoiceForm.vue
- app/javascript/store/modules/invoice.js
- app/policies/batch_create/invoices_policy.rb
- config/locales/policy.en.yml
- config/locales/policy.vi.yml
http://redmine.dtpebike.vn/issues/116
> 116 : Add field "day_lived_per_month" in batch create invoices screen

- app/javascript/api/invoices.js
Add field "day_lived_per_month" in batch create invoices screen
> 116_hotfix: Add field "day_lived_per_month" in batch create invoices screen

- app/assets/stylesheets/_custom_styles.scss
- app/javascript/component_invoices/newInvoices.vue
- app/javascript/component_invoices/rowInvoice.vue
- app/javascript/component_invoices/searchForm.vue
- app/javascript/components/paginator.vue
- app/javascript/contract.vue
- app/javascript/invoice.vue
- app/javascript/locales/modules/en.js
- app/javascript/locales/modules/vi.js
- app/javascript/store/modules/contract.js
- app/javascript/store/modules/invoice.js
- app/javascript/store/modules/user.js
- app/javascript/user.vue
- app/presenters/contracts_presenter.rb
- app/presenters/invoices_presenter.rb
- app/presenters/users_presenter.rb
- app/serializers/contract_list_serializer.rb
- app/serializers/invoice_list_serializer.rb
- app/serializers/user_list_serializer.rb
http://redmine.dtpebike.vn/issues/121
> 121: Search invoice front-end
